### ISSUE TITLE
Composer core SHA issue breaks composer self-update

### ISSUE THREAD

**Issue by lvampa** [ergontech-ansible-roles/composer#5]
See https://github.com/composer/composer/pull/7649

We can't install a version of composer older than 1.8.0 because the fix has only been included in that version so far. 

Without the fix, we can't run self-update to get us to a new version.

**Comment by claudiosanches** [comment]
You need to install again: https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
